### ISSUE TITLE
Is simplejson really necessary as library requirement?

### ISSUE THREAD

**Issue by playpauseandstop** [pyelasticsearch/pyelasticsearch#113]
Hi,

As all you know Python has builtin json support from 2.6 version (I think it is lower supported version of pyelasticsearch), so my question is why you place ``simplejson`` as library requirement?

For support decimals? As you use custom JSON Encoder class is very easy to add decimal conversion there, like:

    def default(self, value):
        ...
        if isinstance(value, decimal.Decimal):
            return str(value)
        ...

For catching json decode errors? I think it easy to swtich from JSONDecodeError to ValueError.

For speed issues? I'm not sure that simplejson much more faster even as much more slower than builtin json. They work about the same. If you need speed you may want look on [https://github.com/esnme/ultrajson](ujson) for example.

So, what is the point of installing and using simplejson, when I'm installing pyelasticsearch?

**Comment by erikrose** [comment]
simplejson is much, much, much faster than the json stdlib module in 2.6, at least. I'm not sure about 2.7. That and use_decimal were the motivations.
