### ISSUE TITLE
Bulk Index Should Break Up Large Requests

### ISSUE THREAD

**Issue by speedplane** [pyelasticsearch/pyelasticsearch#134]
When performing a bulk index, the client builds one massive json structure and sends it off in a single request.  However, on certain platforms (e.g., Google App Engine) HTTP requests are limited in size (in app engine's case to 10MB).  When you request more than that, the request will fail.

To fix the issue on app engine, the bulk indexer should break up the requests into manageable chunks and send one request after the payload reaches a set size.  I understand that this change creates extra requests to be sent, so the chunk size should be configurable and you should be able to turn it off.

I have a fix for this in my branch, I'll issue a pull request shortly.

Thanks

**Comment by erikrose** [comment]
The context manager turned out to be a bad idea, because sending would be triggered on an arbitrary enqueuing operation, so you'd have to wrap each in a try/except if you wanted to handle (or even ignore) any errors. Also, there was no good way to get at the response from the request sent as the context manager exited. So the solution is bulk_chunks(): http://pyelasticsearch.readthedocs.org/en/latest/api/#pyelasticsearch.bulk_chunks.

**Comment by speedplane** [comment]
The problem with these solutions is that you still don't know the size of the indexing request when you make the call.  Although each document should be roughly the same size on average, occasionally, certain documents are much larger than others. 

Suppose you index 10 docs at a time, and most docs are 100k, but there is a 1% chance that a single doc is 10MB. Then one out of a million requests will be 30MB in size and may make the request fail.

To ensure the bulk index is truly reliable, we need a way to measure the size of the object that we're actually sending, and cut off each request once the total size exceeds a predetermined value. The `bulk_chunks` solution does not do that.

**Comment by erikrose** [comment]
That's exactly the situation I have. Actually, the current design does weigh the request and act accordingly. The only thing that makes it "approximate" is that is goes ahead and adds the last doc that puts it "over the limit". If that's enough to break the bank, you could certainly fix it by tweaking bulk_chunks(). I'd take that patch.

**Comment by erikrose** [comment]
There, I couldn't help myself. How's that look to you?
