### ISSUE TITLE
Elastic Search HTTPConnectionPool(host='127.0.0.1', port=9200): Max retries exceeded

### ISSUE THREAD

**Issue by prydie** [pyelasticsearch/pyelasticsearch#143]
I presume this is a bug with my usage of pyelasticsearch, however, I'm completely stumped. Any help would be greatly appreciated.

Details can be found at:
https://stackoverflow.com/questions/21015135/elastic-search-httpconnectionpoolhost-127-0-0-1-port-9200-max-retries-exce?noredirect=1#comment31598214_21015135

Kind regards,
Andrew

**Comment by erikrose** [comment]
We now raise a more relevant error (like ConnectionError) rather than the MaxRetries error that contains it.
