### ISSUE TITLE
ElasticSearch.cluster_state broken with ES >= 1.0

### ISSUE THREAD

**Issue by willkg** [pyelasticsearch/pyelasticsearch#155]
The kwargs arguments for the `_cluster/state` endpoint have changed between 0.90 and 1.0+.

We need to update pyelasticsearch to deprecate the old args and support the new ones. Further, we need to fix the test so that it does one set of things for 0.90 and another set of things for 1.0+.

Elasticsearch 0.90 docs:

http://www.elasticsearch.org/guide/en/elasticsearch/reference/0.90/cluster-state.html

Elasticsearch current docs:

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/cluster-state.html

**Comment by erikrose** [comment]
Fixed in 789d024cda30b4a63fcf7ddf99ae75b7828cd895.
