### ISSUE TITLE
ConnectionError when importing pyelasticsearch

### ISSUE THREAD

**Issue by thatneat** [pyelasticsearch/pyelasticsearch#165]
I'm unable to import pyelasticsearch, due to what seems to be incompatibility with this version of urllib3.

using latest available version of pyelasticsearch from pypi
```
$ pip freeze | grep pyelasticsearch
pyelasticsearch==1.1
```
python and urllib3 versions:
```
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>> urllib3.__version__
'1.7.1'
>>> urllib3.__file__
'/usr/lib/python2.7/dist-packages/urllib3/__init__.pyc'
```
So far so good...
```
>>> import pyelasticsearch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyelasticsearch/__init__.py", line 3, in <module>
    from pyelasticsearch.client import ElasticSearch
  File "/usr/local/lib/python2.7/dist-packages/pyelasticsearch/client.py", line 18, in <module>
    from pyelasticsearch.exceptions import (ElasticHttpError,
  File "/usr/local/lib/python2.7/dist-packages/pyelasticsearch/exceptions.py", line 1, in <module>
    from urllib3.exceptions import TimeoutError as Timeout, ConnectionError
ImportError: cannot import name ConnectionError
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
ImportError: No module named apport.fileutils

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyelasticsearch/__init__.py", line 3, in <module>
    from pyelasticsearch.client import ElasticSearch
  File "/usr/local/lib/python2.7/dist-packages/pyelasticsearch/client.py", line 18, in <module>
    from pyelasticsearch.exceptions import (ElasticHttpError,
  File "/usr/local/lib/python2.7/dist-packages/pyelasticsearch/exceptions.py", line 1, in <module>
    from urllib3.exceptions import TimeoutError as Timeout, ConnectionError
ImportError: cannot import name ConnectionError
```
Note that urllib3 changelog includs a note about renaming ConnectionError: https://pypi.python.org/pypi/urllib3/

**Comment by thatneat** [comment]
Looks like I had some kind of old phantom urllib3 version causing problems. Ran `pip uninstall urllib3` and it looks like I'm good to go!

**Comment by erikrose** [comment]
Thanks for filing this, nonetheless. Sure enough, we do specify `urllib3>=1.8` in setup.py, so it's funny that installing pyelasticsearch didn't trigger a download. Maybe you had a `setup.py develop` installation of urllib3 as well as a `setup.py install` version. That's happened to me before: setuptools thinks you have the latest, but the earlier version is what actually gets imported. Glad you figured it out!

**Comment by delvv** [comment]
Started seeing this same issue (ImportError: cannot import name ConnectionError) after a package update this AM on Ubuntu.  My Ubuntu installation ended up with Urllib3 1.10.4, which doesn't seem to have ConnectionError (it looks like this was replaced by ProtocolError).  Had to delete the system urllib3 package (/usr/lib/python2.7/dist-packages) and ensure that the pip-installed urllib3 (/usr/local/lib/python2.7/dist-packages) was at 1.8.3.  It looks like pyelasticsearch needs to be updated to support the latest urllib3.
