### ISSUE TITLE
ElasticSearch.create_index sends PUT request with body=None

### ISSUE THREAD

**Issue by jimr** [pyelasticsearch/pyelasticsearch#166]
The `send_request` helper defaults `body` to `''`, but `create_index` defaults `body` to `settings`, which in turn, defaults to `None`, so `send_request` ends up with `body=None`. This causes problems when going down to `httplib` via `urllib3` because `httplib` doesn't set a `Content-Length` header for any requests where the `body` is `None`. All of this amounts to 411 responses from nginx when using that as a proxy for ElasticSearch.

I've actually submitted a bug report for Python[1] because I think that even with `body=None`, `httplib` should set the `Content-Length` header for methods that expect a body (`PATCH`, `POST`, and `PUT`) but in the meantime, we could avoid the issue either by not passing `body` to `send_request` from `create_index` if it's `None`, or (even better) have some logic inside `send_request` that defaults `body` to `None` and sets it to `''` if that's how it comes in.

[1] http://bugs.python.org/issue23539

**Comment by erikrose** [comment]
Great bug report. Thanks! Fixing it now.

**Comment by jimr** [comment]
Thanks for the speedy fix & version bump.

**Comment by erikrose** [comment]
You're welcome! Pushed 1.2: https://pypi.python.org/pypi/pyelasticsearch/
