### ISSUE TITLE
pyES sends encoded JSON, which ES cannot decode

### ISSUE THREAD

**Issue by tpievila** [pyelasticsearch/pyelasticsearch#169]
Currently ES does not handle \u escape mechanism for Basic Multilingual Plane, but pyES does not specify ensure_ascii=False when dumping to JSON.

**Comment by tpievila** [comment]
Mea culpa. Didn't verify how curl encodes non-ascii chars in URLs, if not written out already encoded. Both ES and pyelasticsearch work fine.

**Comment by erikrose** [comment]
Oh, good. Thanks for following up!
