### ISSUE TITLE
send_request fails when optional parameter query_params is not initialized as {}

### ISSUE THREAD

**Issue by anoeee** [pyelasticsearch/pyelasticsearch#173]
Code expects dictionary to be initialized in client.py line 246:

params=dict((k, self._utf8(self._to_query(v)))
                            for k, v in iteritems(query_params)),
                body=body)

Will only work if called:
   self.send_request('GET',path_components, doc, {})
and should work:
  self.send_request('GET',path_components, doc)

Optional parameter should be:
def send_request(self,
                     method,
                     path_components,
                     body='',
                     query_params={}):

**Comment by erikrose** [comment]
Thanks for the report!
