### ISSUE TITLE
Connection timeout when connecting over https

### ISSUE THREAD

**Issue by drcongo** [pyelasticsearch/pyelasticsearch#175]
I'm having trouble getting pyelasticsearch to connect over https (my ES server is proxied behind nginx with basic auth). Digging through the source, I found that you're using elasticsearch-py's transport layer, so I did some testing with that directly and it connects absolutely fine...

    from elasticsearch import Elasticsearch
    from pyelasticsearch import ElasticSearch

    esconf = {
        'protocol': 'https',
        'url': 'elastic.mydomain.com',
        'port': '443',
        'basicauth_user': 'basicauthuser',
        'basicauth_pass': 'basicauthpass'
    }

    surl = '{}://{}:{}@{}:{}/'.format(esconf['protocol'],
                                                      esconf['basicauth_user'],
                                                      esconf['basicauth_pass'],
                                                      esconf['url'],
                                                      esconf['port'])

    espy.info()

    #{u'name': u'Commando', u'status': 200, u'tagline': u'You Know, for Search',
    # u'version': {u'build_hash': u'e511f7b28b77c4d99175905fac65bffbf4c80cf7',
    # u'build_snapshot': False, u'build_timestamp': u'2014-05-22T12:27:39Z',
    # u'lucene_version': u'4.7', u'number': u'1.1.2'}}

    pyes = ElasticSearch(surl)
    pyes.health()

    # ElasticHttpError: (400, u'<html>\r\n<head><title>400 The plain HTTP request
    # was sent to HTTPS port</title></head>\r\n<body bgcolor="white">\r\n<center>
    # <h1>400 Bad Request</h1></center>\r\n<center>The plain HTTP request was sent
    # to HTTPS port</center>\r\n<hr><center>nginx/1.8.0</center>\r\n</body>\r\n</html>\r\n')

Is there a way to tell pyelasticsearch to use the https functionality in elasticsearch-py?

**Comment by erikrose** [comment]
I'm adding facilities to recognize HTTPS URLs and just Do The Right Thing right now. The tricky bit is where to find CA certs to verify against. I certainly don't want to default to not verifying, but it's nigh impossible to get the system bundle on OS X or Windows. The Requests transport handles it well, but it's a lot slower than urllib3 IIRC. Having a look at https://pypi.python.org/pypi/certifi/ now.

**Comment by erikrose** [comment]
Yes, certifi seems the way to go. They keep it pretty up to date. We have the option of using the POSIX-like store as a first resort later if we like, but this is simple and reliable for a start.

**Comment by erikrose** [comment]
Does [this](https://github.com/pyelasticsearch/pyelasticsearch/commit/724d845472e495546c43c2349858ee006ff1baea) (the latest master) do it for you?

**Comment by drcongo** [comment]
Hey Eric, thanks for the speed of that! I'll do some testing as soon as I get a chance. I've currently worked around it by using elasticsearch-py directly but I much prefer the API of pyelasticsearch.

**Comment by erikrose** [comment]
Great! Once we know it works for you, let me know, and I'll cut a release.

**Comment by drcongo** [comment]
Hey Erik (spelled correctly this time, sorry). This certainly seems to work, thank you. impressive turnaround!

**Comment by drcongo** [comment]
Phenomenal work sir.

**Comment by erikrose** [comment]
Thanks for using the lib! And I neglected to mention it, but version 1.3 is up on PyPI with this fix.
