### ISSUE TITLE
Certifi has problem to verify SSL

### ISSUE THREAD

**Issue by mrteera** [pyelasticsearch/pyelasticsearch#181]
I found that pyelasticsearch depends on certifi. It'll break `requests.get` with some HTTPS site. Here's the issue on certifi https://github.com/certifi/python-certifi/issues/26

The current workaround if I want to verify is I need to specify CA bundle file everywhere I use `requests.get`.
```
requests.get('https://s3-eu-west-1.amazonaws.com/..', verify='/etc/ssl/certs/ca-certificates.crt')
```
or
```
requests.get('https://s3-eu-west-1.amazonaws.com/..', verify=certifi.old_where())
```

**Comment by mrteera** [comment]
Ah, I just found the reason here: https://github.com/certifi/python-certifi/issues/26#issuecomment-147962495
This might be Amazon issue that they use SHA-1 cert for S3.

**Comment by erikrose** [comment]
Ouch! SHA1? That's bad news if that's true.
