### ISSUE TITLE
Connect to AWS using IAM?

### ISSUE THREAD

**Issue by brianmingus** [pyelasticsearch/pyelasticsearch#191]
The official elasticsearch client gives an example of connecting to AWS ES using IAM - can pyelasticsearch do that?

**Comment by erikrose** [comment]
I don't know. How are IAM credentials passed?

**Comment by brianmingus** [comment]
I've decided to use superelasticsearch, since it supports bulk operations by simply modifying the official elasticsearch client, which preserves the ability to connect via IAM
