### ISSUE TITLE
Pull the urllib3-native exception out, and raise it

### ISSUE THREAD

**Issue by Korun1** [pyelasticsearch/pyelasticsearch#196]

**Comment by Korun1** [comment]
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Traceback (most recent call last):
  File "delete_index.py", line 27, in <module>
    delete_index(res,line)
  File "delete_index.py", line 10, in delete_index
    es.delete_index(index=idx)
  File "../pyelasticsearch/client.py", line 93, in decorate
    return func(*args, query_params=query_params, **kwargs)
  File "../pyelasticsearch/client.py", line 1054, in delete_index
    query_params=query_params)
  File "../pyelasticsearch/client.py", line 281, in send_request
    raise exc.info


Pull the urllib3-native exception out, and raise it


My server does not have access to the external network access, this code need pull code?

**Comment by Korun1** [comment]
Thank you for your reply！
I mean, I cloned the code in my server, but my linux server can not connect to the network, so I run failed. Does pyelasticsearch need to be connected to the network to run normally?

**Comment by erikrose** [comment]
pyelasticsearch uses HTTPS only if you start your node addresses with "https://" in the config. It looks like your build of Python doesn't support HTTPS/SSL, so you'll either need to upgrade/rebuild Python or connect to ES over plain HTTP.
