### ISSUE TITLE
bulk ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by fikfok** [pyelasticsearch/pyelasticsearch#197]
Hello!
 I'm trying to write code to insert documents using bulk. It is based on this description: http://pyelasticsearch.readthedocs.io/en/latest/api/#pyelasticsearch.ElasticSearch.bulk

My code:
```
>>> from pyelasticsearch import ElasticSearch
>>> es = ElasticSearch()
>>> es.bulk([es.index_op(doc={'id': 1, 'color': 'red'}), es.index_op(doc={'id': 2, 'color': 'green'})], doc_type='test10', index='test10')
```

Python returns this error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fikfok/test_env/lib/python3.5/site-packages/pyelasticsearch/client.py", line 93, in decorate
    return func(*args, query_params=query_params, **kwargs)
  File "/home/fikfok/test_env/lib/python3.5/site-packages/pyelasticsearch/client.py", line 447, in bulk
    query_params=query_params)
  File "/home/fikfok/test_env/lib/python3.5/site-packages/pyelasticsearch/client.py", line 276, in send_request
    body=body)
ValueError: too many values to unpack (expected 2)
```

But it inserts these documents into Elasticsearch.

What I use:
```
Linux Mint 18.1
Elasticsearch 5.5.0 (engine)
virtualenv
Python 3.5.2
pyelasticsearch 1.4
elasticsearch 5.4.0 (package in virtual env "test_env")
```

Please tell me where I'm wrong and how to fix the error. Thanks!

**Comment by erikrose** [comment]
Hmm, I suspected that the `elasticsearch` lib had changed its method signature and broken our `perform_request()` call, but it hasn't. I'm not sure what's going on. It might be interesting to step through that in pdb and see if anything clearer emerges. Perhaps somebody is catching and re-throwing an exception, and it's losing its context.

**Comment by fikfok** [comment]
I am new in Python, so for me it will not be easy to apply your advice.
Аnyway thank you very much for the answer!
