### ISSUE TITLE
Python 3.6 release

### ISSUE THREAD

**Issue by hsmett** [pyelasticsearch/pyelasticsearch#199]
Hello @erikrose !
First, let me thank you for amazing work here ! :1st_place_medal: 
I was wondering if / when you plan to publish a release including the Python 3.6 fixes?

Thx!

**Comment by erikrose** [comment]
Yes! Though it might be next week, as I’m in an intensive sprint this week.

**Comment by hsmett** [comment]
Great!

**Comment by hsmett** [comment]
v1.4.1 (2018-04-02)
Thank you very much @erikrose !
