### ISSUE TITLE
Update bulk_index to enable all options

### ISSUE THREAD

**Issue by HonzaKral** [pyelasticsearch/pyelasticsearch#83]
We currently cannot:
* use _parent, _routing, _ttl and other fields from http://www.elasticsearch.org/guide/reference/api/bulk.html in the action
* specify different index/doc_type per document

The same interface design should be then used for the multi_get proposal (#37) and would fix #68.

-- (Erik starts talking here.) --

Using http://www.elasticsearch.org/guide/reference/api/bulk.html as an example, here are where various params need to land. As you can see, we have quite a lawn-sprinkler effect.

In doc:
* parent
* ttl
* id
* timestamp
* version

In meta:
* percolator
* index
* doc_type

Dunno:
* version_type

Once per bulk call:
* refresh
* consistency

Problem: right now, `index` and `doc_type` are required args for `bulk_index`. These need to be optional so they can be specified per document. But `docs` needs to be required, so the argument order needs to change. Fun! We might end up making a whole new routine to handle the power-user cases.

Rather than muck up (and break backward compatibility of) `bulk_index` for the unusual power-user use case, we'll introduce a new routine, `bulk`, which does arbitrary bulk operations. Then the naming is more accurate anyway. It might look something like this:

    def bulk(self, docs, index=None, doc_type=None, id_field='id' (maybe this should die)):
        """
        :arg docs: An iterable of things, each of which is either a dict representing a doc or a tuple (or something, maybe) representing (action dict, doc dict). Or something or something.
        """

**Comment by erikrose** [comment]
Done.
